# Generated by Django 4.1.1 on 2022-11-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(help_text='Сотрудник', max_length=100, verbose_name='Worker')),
                ('position', models.CharField(choices=[('secretary', 'Секретарь'), ('accountant', 'Бухгалтер'), ('developer', 'Разработчик'), ('manager', 'Менеджер'), ('engineer', 'Инженер'), ('sys_admin', 'Системный администратор'), ('director', 'Директор')], help_text='Должность', max_length=100, verbose_name='Position')),
                ('salary', models.IntegerField(help_text='Зарплата', verbose_name='Salary')),
                ('full_time', models.BooleanField(default=True, help_text='Полная занятость', verbose_name='Full time')),
            ],
            options={
                'verbose_name': 'Worker',
                'db_table': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_hours_week', models.IntegerField(help_text='Кол-во рабочих часов в день', verbose_name='Amount of hours a day')),
                ('am_days_week', models.IntegerField(help_text='Кол-во рабочих дней в неделю', verbose_name='Amount of days a week')),
                ('am_weekends_week', models.IntegerField(help_text='Кол-во выходных в неделю', verbose_name='Amount of weekends a week')),
                ('full_time', models.ForeignKey(help_text='Работник', null=True, on_delete=django.db.models.deletion.CASCADE, to='workerStuff.workers', verbose_name='Full time worker')),
            ],
            options={
                'verbose_name': 'WorkHours',
                'db_table': 'WorkHours',
            },
        ),
        migrations.CreateModel(
            name='VacationsWeekends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_vacations_year', models.IntegerField(help_text='Кол-во отпусков в году', verbose_name='Amount of vacations a year')),
                ('am_days_vacation', models.IntegerField(help_text='Кол-во дней в 1 отпуске', verbose_name='Amount of days in a vacation')),
                ('am_weekends_week', models.ForeignKey(help_text='Кол-во выходных в неделю', null=True, on_delete=django.db.models.deletion.CASCADE, to='workerStuff.workhours', verbose_name='Amount of weekends a week')),
            ],
            options={
                'verbose_name': 'Vacations and Weekends',
                'db_table': 'VacationsWeekends',
            },
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(help_text='Задача', max_length=100, unique=True, verbose_name='Task')),
                ('is_done', models.CharField(choices=[('YES', 'YES'), ('HALF', 'HALF'), ('NO', 'NO'), ('ALMOST', 'ALMOST')], default='NO', help_text='Завершено', max_length=6, verbose_name='Is done')),
                ('deadline', models.DateField(help_text='Сроки сдачи', verbose_name='Deadlines')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workerStuff.workers', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Duty',
                'db_table': 'Duties',
            },
        ),
    ]
