# Generated by Django 4.1.1 on 2022-12-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workerStuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties',
            name='is_done',
            field=models.CharField(choices=[('ALMOST', 'ALMOST'), ('NO', 'NO'), ('YES', 'YES'), ('HALF', 'HALF')], default='NO', help_text='Завершено', max_length=6, verbose_name='Is done'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='position',
            field=models.CharField(help_text='Должность', max_length=100, verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='имя пользователя', max_length=50, verbose_name='name')),
                ('email', models.CharField(help_text='почта пользователя', max_length=50, verbose_name='email')),
                ('theme', models.CharField(max_length=50, verbose_name='Tема обращения')),
                ('description_of_problem', models.CharField(help_text='Опишите свою проблему', max_length=300, verbose_name='Oбращение')),
                ('worker', models.ForeignKey(help_text='Сотрудник', null=True, on_delete=django.db.models.deletion.CASCADE, to='workerStuff.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Requests',
                'db_table': 'Requests',
            },
        ),
    ]
